apiVersion: v2
name: cuemby-odoo
description: Cuemby wrapper chart for Odoo (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "18.0.20250805"

dependencies:
  - name: odoo
    version: "28.2.10"
    repository: oci://registry-1.docker.io/bitnamicharts
