apiVersion: v1
kind: Secret
metadata:
  name: n8n-db-secret
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${PARAM_N8N_DB_PASSWORD}"
  POSTGRES_USER: "n8n"
  POSTGRES_DB: "n8n"
  N8N_ENCRYPTION_KEY: "${PARAM_N8N_ENCRYPTION_KEY}"
