apiVersion: v1
kind: Service
metadata:
  name: n8n
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: app
  ports:
    - port: 5678
      targetPort: 5678
      nodePort: ${PARAM_N8N_NODEPORT}
      protocol: TCP
