apiVersion: v1
kind: Service
metadata:
  name: n8n-http
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: 5678
      protocol: TCP
