apiVersion: v1
kind: Secret
metadata:
  name: nats-jetstream-credentials
  labels:
    app.kubernetes.io/name: nats-jetstream
    app.kubernetes.io/component: database
type: Opaque
stringData:
  NATS_AUTH_TOKEN: "${PARAM_NATS_AUTH_TOKEN}"
