apiVersion: v1
kind: Service
metadata:
  name: nats-jetstream
  labels:
    app.kubernetes.io/name: nats-jetstream
    app.kubernetes.io/component: database
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nats-jetstream
    app.kubernetes.io/component: database
  ports:
    - port: 4222
      targetPort: 4222
      nodePort: ${PARAM_NATS_CLIENT_NODEPORT}
      protocol: TCP
