apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-data
  labels:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/component: portainer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: ${PARAM_PORTAINER_DATA_SIZE}
