apiVersion: v1
kind: Service
metadata:
  name: portainer
  labels:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/component: portainer
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/component: portainer
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: ${PARAM_PORTAINER_NODEPORT}
      protocol: TCP
