apiVersion: v1
kind: Service
metadata:
  name: portainer-http
  labels:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/component: portainer
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/component: portainer
  ports:
    - name: http
      port: 80
      targetPort: 9000
      protocol: TCP
