apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-credentials
  labels:
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/component: registry
type: Opaque
stringData:
  REGISTRY_HTTP_SECRET: "${PARAM_REGISTRY_HTTP_SECRET}"
