apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-data
  labels:
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/component: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: ${PARAM_REGISTRY_DATA_SIZE}
