apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/component: registry
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/component: registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: ${PARAM_REGISTRY_NODEPORT}
      protocol: TCP
