apiVersion: v2
name: cuemby-matomo
description: Cuemby wrapper chart for Matomo (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "5.3.1"

dependencies:
  - name: matomo
    version: "11.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
