apiVersion: v1
kind: Secret
metadata:
  name: code-server-credentials
  labels:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/component: code-server
type: Opaque
stringData:
  PASSWORD: "${PARAM_CODE_SERVER_PASSWORD}"
