apiVersion: v1
kind: Service
metadata:
  name: code-server
  labels:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/component: code-server
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/component: code-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: ${PARAM_CODE_SERVER_NODEPORT}
      protocol: TCP
