apiVersion: v1
kind: Service
metadata:
  name: code-server-http
  labels:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/component: code-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/component: code-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
