apiVersion: v2
name: cuemby-moodle
description: Cuemby wrapper chart for Moodle (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "4.5.2"

dependencies:
  - name: moodle
    version: "28.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
