apiVersion: v1
kind: Secret
metadata:
  name: owncloud-db-secret
  labels:
    app.kubernetes.io/name: owncloud
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "${PARAM_OWNCLOUD_DB_ROOT_PASSWORD}"
  MYSQL_DATABASE: "owncloud"
  MYSQL_USER: "owncloud"
  MYSQL_PASSWORD: "${PARAM_OWNCLOUD_DB_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: owncloud-valkey-secret
  labels:
    app.kubernetes.io/name: owncloud
    app.kubernetes.io/component: cache
type: Opaque
stringData:
  VALKEY_PASSWORD: "${PARAM_OWNCLOUD_VALKEY_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: owncloud-app-secret
  labels:
    app.kubernetes.io/name: owncloud
    app.kubernetes.io/component: app
type: Opaque
stringData:
  OWNCLOUD_ADMIN_USERNAME: "${PARAM_OWNCLOUD_ADMIN_USERNAME}"
  OWNCLOUD_ADMIN_PASSWORD: "${PARAM_OWNCLOUD_ADMIN_PASSWORD}"
