apiVersion: v1
kind: Service
metadata:
  name: owncloud-mariadb
  labels:
    app.kubernetes.io/name: owncloud
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: owncloud
    app.kubernetes.io/component: database
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
