apiVersion: v1
kind: Service
metadata:
  name: owncloud-valkey
  labels:
    app.kubernetes.io/name: owncloud
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: owncloud
    app.kubernetes.io/component: cache
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
