apiVersion: v1
kind: Service
metadata:
  name: owncloud
  labels:
    app.kubernetes.io/name: owncloud
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: owncloud
    app.kubernetes.io/component: app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: ${PARAM_HTTP_NODEPORT}
      protocol: TCP
