apiVersion: v1
kind: Service
metadata:
  name: owncloud-http
  labels:
    app.kubernetes.io/name: owncloud
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: owncloud
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
