#cloud-config
package_update: true

packages:
  - curl
  - git
  - jq

write_files:
  - path: /opt/cuemby/marketplace-env.sh
    permissions: "0600"
    content: |
      #!/usr/bin/env bash
      export APP_NAME="vaultwarden"
      export APP_VERSION="{{app-version}}"
      export PARAM_VAULTWARDEN_ADMIN_TOKEN="{{param-vaultwarden-admin-token}}"
      export PARAM_VAULTWARDEN_DATA_SIZE="{{param-vaultwarden-data-size}}"
      export PARAM_VAULTWARDEN_SSL_ENABLED="{{param-vaultwarden-ssl-enabled}}"
      export PARAM_VAULTWARDEN_HOSTNAME="{{param-vaultwarden-hostname}}"

runcmd:
  - git clone https://github.com/cuemby/cloud-marketplace.git /opt/cuemby/marketplace
  - [bash, -c, "source /opt/cuemby/marketplace-env.sh && /opt/cuemby/marketplace/bootstrap/entrypoint.sh 2>&1 | tee /var/log/cuemby/bootstrap.log"]
