apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: database
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "${PARAM_RABBITMQ_DEFAULT_USER}"
  RABBITMQ_DEFAULT_PASS: "${PARAM_RABBITMQ_DEFAULT_PASS}"
