apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: database
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: database
  ports:
    - port: 5672
      targetPort: 5672
      nodePort: ${PARAM_RABBITMQ_AMQP_NODEPORT}
      protocol: TCP
