apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: database
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: database
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: ${PARAM_RABBITMQ_MANAGEMENT_NODEPORT}
      protocol: TCP
