apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-web
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: database
  ports:
    - name: http
      port: 80
      targetPort: 15672
      protocol: TCP
