apiVersion: v1
kind: Secret
metadata:
  name: mlflow-db-secret
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${PARAM_MLFLOW_DB_PASSWORD}"
  POSTGRES_USER: "mlflow"
  POSTGRES_DB: "mlflow"
