apiVersion: v1
kind: Service
metadata:
  name: mlflow
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: ${PARAM_MLFLOW_NODEPORT}
      protocol: TCP
