apiVersion: v1
kind: Service
metadata:
  name: mlflow-http
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
