apiVersion: v2
name: cuemby-postgresql
description: Cuemby wrapper chart for PostgreSQL (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "18.2.0"

dependencies:
  - name: postgresql
    version: "18.3.0"
    repository: oci://registry-1.docker.io/bitnamicharts
