apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${PARAM_POSTGRES_PASSWORD}"
  POSTGRES_USER: "${PARAM_POSTGRES_USER}"
  POSTGRES_DB: "${PARAM_POSTGRES_DB}"
