apiVersion: v2
name: cuemby-minio
description: Cuemby wrapper chart for MinIO (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "2025.7.23"

dependencies:
  - name: minio
    version: "17.0.21"
    repository: oci://registry-1.docker.io/bitnamicharts
