apiVersion: v2
name: cuemby-jupyterhub
description: Cuemby wrapper chart for JupyterHub (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "5.3.0"

dependencies:
  - name: jupyterhub
    version: "10.0.5"
    repository: oci://registry-1.docker.io/bitnamicharts
