apiVersion: v2
name: cuemby-opensearch
description: Cuemby wrapper chart for OpenSearch (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "3.2.0"

dependencies:
  - name: opensearch
    version: "2.0.10"
    repository: oci://registry-1.docker.io/bitnamicharts
