apiVersion: apps/v1
kind: Deployment
metadata:
  name: coolify-soketi
  labels:
    app.kubernetes.io/name: coolify
    app.kubernetes.io/component: websocket
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: coolify
      app.kubernetes.io/component: websocket
  template:
    metadata:
      labels:
        app.kubernetes.io/name: coolify
        app.kubernetes.io/component: websocket
    spec:
      containers:
        - name: soketi
          image: quay.io/soketi/soketi:1.6-16-debian
          env:
            - name: SOKETI_DEFAULT_APP_ID
              valueFrom:
                secretKeyRef:
                  name: coolify-app-secret
                  key: PUSHER_APP_ID
            - name: SOKETI_DEFAULT_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: coolify-app-secret
                  key: PUSHER_APP_KEY
            - name: SOKETI_DEFAULT_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: coolify-app-secret
                  key: PUSHER_APP_SECRET
            - name: SOKETI_DEBUG
              value: "false"
          ports:
            - containerPort: 6001
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: 6001
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 15
          livenessProbe:
            tcpSocket:
              port: 6001
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 6001
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: ${PARAM_COOLIFY_SOKETI_CPU_REQUEST}
              memory: ${PARAM_COOLIFY_SOKETI_MEMORY_REQUEST}
            limits:
              cpu: ${PARAM_COOLIFY_SOKETI_CPU_LIMIT}
              memory: ${PARAM_COOLIFY_SOKETI_MEMORY_LIMIT}
