apiVersion: v1
kind: Service
metadata:
  name: coolify-redis
  labels:
    app.kubernetes.io/name: coolify
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: coolify
    app.kubernetes.io/component: cache
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
