apiVersion: v1
kind: Service
metadata:
  name: coolify
  labels:
    app.kubernetes.io/name: coolify
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: coolify
    app.kubernetes.io/component: app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: ${PARAM_COOLIFY_NODEPORT}
      protocol: TCP
