apiVersion: v1
kind: Secret
metadata:
  name: percona-mysql-credentials
  labels:
    app.kubernetes.io/name: percona-mysql
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "${PARAM_PERCONA_ROOT_PASSWORD}"
  MYSQL_USER: "${PARAM_PERCONA_USER}"
  MYSQL_PASSWORD: "${PARAM_PERCONA_PASSWORD}"
  MYSQL_DATABASE: "${PARAM_PERCONA_DATABASE}"
