apiVersion: v1
kind: Service
metadata:
  name: percona-mysql
  labels:
    app.kubernetes.io/name: percona-mysql
    app.kubernetes.io/component: database
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: percona-mysql
    app.kubernetes.io/component: database
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: ${PARAM_PERCONA_NODEPORT}
      protocol: TCP
