apiVersion: v1
kind: Secret
metadata:
  name: valkey-credentials
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/component: database
type: Opaque
stringData:
  VALKEY_PASSWORD: "${PARAM_VALKEY_PASSWORD}"
