apiVersion: v1
kind: Service
metadata:
  name: valkey
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/component: database
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/component: database
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: ${PARAM_VALKEY_NODEPORT}
      protocol: TCP
