apiVersion: v2
name: cuemby-mariadb
description: Cuemby wrapper chart for MariaDB (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "12.2.2"

dependencies:
  - name: mariadb
    version: "25.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
