apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app.kubernetes.io/name: selenium
    app.kubernetes.io/component: hub
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: selenium
      app.kubernetes.io/component: hub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: selenium
        app.kubernetes.io/component: hub
    spec:
      containers:
        - name: selenium-hub
          image: "docker.io/selenium/hub:${PARAM_APP_IMAGE_TAG}"
          ports:
            - name: http
              containerPort: 4444
              protocol: TCP
            - name: publish
              containerPort: 4442
              protocol: TCP
            - name: subscribe
              containerPort: 4443
              protocol: TCP
          env:
            - name: SE_NODE_GRID_URL
              value: "http://selenium-hub:4444"
          startupProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: ${PARAM_SELENIUM_HUB_CPU_REQUEST}
              memory: ${PARAM_SELENIUM_HUB_MEMORY_REQUEST}
            limits:
              cpu: ${PARAM_SELENIUM_HUB_CPU_LIMIT}
              memory: ${PARAM_SELENIUM_HUB_MEMORY_LIMIT}
