apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    app.kubernetes.io/name: selenium
    app.kubernetes.io/component: hub
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: selenium
    app.kubernetes.io/component: hub
  ports:
    - name: http
      port: 4444
      targetPort: 4444
      nodePort: ${PARAM_SELENIUM_HUB_NODEPORT}
      protocol: TCP
    - name: publish
      port: 4442
      targetPort: 4442
      protocol: TCP
    - name: subscribe
      port: 4443
      targetPort: 4443
      protocol: TCP
