apiVersion: v1
kind: Service
metadata:
  name: selenium-http
  labels:
    app.kubernetes.io/name: selenium
    app.kubernetes.io/component: hub
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: selenium
    app.kubernetes.io/component: hub
  ports:
    - name: http
      port: 80
      targetPort: 4444
      protocol: TCP
