apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db-secret
  labels:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${PARAM_SONARQUBE_DB_PASSWORD}"
  POSTGRES_USER: "sonarqube"
  POSTGRES_DB: "sonarqube"
