apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/component: app
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: ${PARAM_SONARQUBE_NODEPORT}
      protocol: TCP
