apiVersion: v1
kind: Service
metadata:
  name: sonarqube-http
  labels:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: 9000
      protocol: TCP
