apiVersion: v2
name: cuemby-superset
description: Cuemby wrapper chart for Superset (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "5.0.0"

dependencies:
  - name: superset
    version: "5.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
