#cloud-config
# Cloud-init user-data for deploying APPNAME via Cuemby Cloud Marketplace.
#
# Parameters can be set as environment variables in the write_files section below,
# or they will use the default values shown.

package_update: true
package_upgrade: true

packages:
  - curl
  - git
  - jq

write_files:
  - path: /opt/cuemby/marketplace-env.sh
    permissions: "0600"
    content: |
      #!/usr/bin/env bash
      export APP_NAME="APPNAME"
      export APP_VERSION="${APP_VERSION:-CHANGE_ME}"
      export PARAM_EXAMPLE_PARAM="${PARAM_EXAMPLE_PARAM:-CHANGE_ME}"

runcmd:
  - git clone https://github.com/cuemby/cloud-marketplace.git /opt/cuemby/marketplace
  - [bash, -c, "source /opt/cuemby/marketplace-env.sh && /opt/cuemby/marketplace/bootstrap/entrypoint.sh 2>&1 | tee /var/log/cuemby/bootstrap.log"]
