apiVersion: v2
name: cuemby-jaeger
description: Cuemby wrapper chart for Jaeger (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "2.9.0"

dependencies:
  - name: jaeger
    version: "6.0.5"
    repository: oci://registry-1.docker.io/bitnamicharts
