apiVersion: v2
name: cuemby-rabbitmq
description: Cuemby wrapper chart for RabbitMQ (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "4.1.3"

dependencies:
  - name: rabbitmq
    version: "16.0.14"
    repository: oci://registry-1.docker.io/bitnamicharts
