apiVersion: v1
kind: Service
metadata:
  name: openclaw
  labels:
    app.kubernetes.io/name: openclaw
    app.kubernetes.io/component: gateway
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: openclaw
    app.kubernetes.io/component: gateway
  ports:
    - port: 18789
      targetPort: 18789
      nodePort: ${PARAM_OPENCLAW_NODEPORT}
      protocol: TCP
