apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: app
  ports:
    - port: 50000
      targetPort: 50000
      nodePort: ${PARAM_JENKINS_AGENT_NODEPORT}
      protocol: TCP
