apiVersion: v1
kind: Service
metadata:
  name: jenkins-web
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
