apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-credentials
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/component: vaultwarden
type: Opaque
stringData:
  ADMIN_TOKEN: "${PARAM_VAULTWARDEN_ADMIN_TOKEN}"
