apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/component: vaultwarden
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/component: vaultwarden
  ports:
    - port: 80
      targetPort: 80
      nodePort: ${PARAM_VAULTWARDEN_NODEPORT}
      protocol: TCP
