apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-http
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/component: vaultwarden
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/component: vaultwarden
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
