apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: database
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: database
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: ${PARAM_KAFKA_NODEPORT}
      protocol: TCP
