apiVersion: v2
name: cuemby-clickhouse
description: Cuemby wrapper chart for ClickHouse (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "25.7.5"

dependencies:
  - name: clickhouse
    version: "9.4.4"
    repository: oci://registry-1.docker.io/bitnamicharts
