apiVersion: v2
name: cuemby-elasticsearch
description: Cuemby wrapper chart for Elasticsearch (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "8.17.0"

dependencies:
  - name: elasticsearch
    version: "22.1.6"
    repository: oci://registry-1.docker.io/bitnamicharts
