apiVersion: v2
name: cuemby-mlflow
description: Cuemby wrapper chart for MLflow (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "2.20.2"

dependencies:
  - name: mlflow
    version: "5.1.17"
    repository: oci://registry-1.docker.io/bitnamicharts
