apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "${PARAM_MARIADB_ROOT_PASSWORD}"
  MARIADB_USER: "${PARAM_MARIADB_USER}"
  MARIADB_PASSWORD: "${PARAM_MARIADB_PASSWORD}"
  MARIADB_DATABASE: "${PARAM_MARIADB_DATABASE}"
