apiVersion: v2
name: cuemby-keycloak
description: Cuemby wrapper chart for Keycloak (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "26.3.3"

dependencies:
  - name: keycloak
    version: "25.2.0"
    repository: oci://registry-1.docker.io/bitnamicharts
