apiVersion: v1
kind: Secret
metadata:
  name: opensearch-credentials
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/component: database
type: Opaque
stringData:
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "${PARAM_OPENSEARCH_PASSWORD}"
