apiVersion: v1
kind: Service
metadata:
  name: opensearch
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/component: database
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/component: database
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: ${PARAM_OPENSEARCH_NODEPORT}
      protocol: TCP
