apiVersion: v1
kind: Service
metadata:
  name: opensearch-http
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/component: database
  ports:
    - name: http
      port: 80
      targetPort: 9200
      protocol: TCP
