apiVersion: v1
kind: Secret
metadata:
  name: kong-db-secret
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${PARAM_KONG_DB_PASSWORD}"
  POSTGRES_USER: "kong"
  POSTGRES_DB: "kong"
