apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: app
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      nodePort: ${PARAM_KONG_PROXY_NODEPORT}
      protocol: TCP
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
      protocol: TCP
