apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: app
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: ${PARAM_KONG_ADMIN_NODEPORT}
      protocol: TCP
