apiVersion: v1
kind: Service
metadata:
  name: kong-proxy-http
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
