apiVersion: v2
name: cuemby-cassandra
description: Cuemby wrapper chart for Cassandra (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "5.0.5"

dependencies:
  - name: cassandra
    version: "12.3.11"
    repository: oci://registry-1.docker.io/bitnamicharts
