apiVersion: v2
name: cuemby-mastodon
description: Cuemby wrapper chart for Mastodon (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "4.4.3"

dependencies:
  - name: mastodon
    version: "14.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
