apiVersion: v1
kind: Secret
metadata:
  name: couchdb-credentials
  labels:
    app.kubernetes.io/name: couchdb
    app.kubernetes.io/component: database
type: Opaque
stringData:
  COUCHDB_USER: "${PARAM_COUCHDB_USER}"
  COUCHDB_PASSWORD: "${PARAM_COUCHDB_PASSWORD}"
