apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    app.kubernetes.io/name: couchdb
    app.kubernetes.io/component: database
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: couchdb
    app.kubernetes.io/component: database
  ports:
    - port: 5984
      targetPort: 5984
      nodePort: ${PARAM_COUCHDB_NODEPORT}
      protocol: TCP
