apiVersion: v2
name: cuemby-nginx
description: Cuemby wrapper chart for NGINX (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "1.27.4"

dependencies:
  - name: nginx
    version: "22.5.0"
    repository: oci://registry-1.docker.io/bitnamicharts
