apiVersion: v1
kind: Secret
metadata:
  name: devtron-secret
  labels:
    app.kubernetes.io/name: devtron
    app.kubernetes.io/component: app
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${PARAM_DEVTRON_DB_PASSWORD}"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "orchestrator"
  PG_PASSWORD: "${PARAM_DEVTRON_DB_PASSWORD}"
  ADMIN_PASSWORD: "${PARAM_DEVTRON_ADMIN_PASSWORD}"
