apiVersion: v1
kind: Service
metadata:
  name: devtron-orchestrator
  labels:
    app.kubernetes.io/name: devtron
    app.kubernetes.io/component: orchestrator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: devtron
    app.kubernetes.io/component: orchestrator
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
