apiVersion: v1
kind: Secret
metadata:
  name: twenty-db-secret
  labels:
    app.kubernetes.io/name: twenty
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${PARAM_TWENTY_DB_PASSWORD}"
  POSTGRES_USER: "twenty"
  POSTGRES_DB: "default"
---
apiVersion: v1
kind: Secret
metadata:
  name: twenty-app-secret
  labels:
    app.kubernetes.io/name: twenty
    app.kubernetes.io/component: app
type: Opaque
stringData:
  APP_SECRET: "${PARAM_TWENTY_APP_SECRET}"
