apiVersion: v1
kind: Service
metadata:
  name: twenty
  labels:
    app.kubernetes.io/name: twenty
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: twenty
    app.kubernetes.io/component: app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: ${PARAM_HTTP_NODEPORT}
      protocol: TCP
