apiVersion: v1
kind: Service
metadata:
  name: twenty-http
  labels:
    app.kubernetes.io/name: twenty
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: twenty
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
