apiVersion: v2
name: cuemby-phpmyadmin
description: Cuemby wrapper chart for phpMyAdmin (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "5.2.2"

dependencies:
  - name: phpmyadmin
    version: "20.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
