apiVersion: v1
kind: Secret
metadata:
  name: cassandra-credentials
  labels:
    app.kubernetes.io/name: cassandra
    app.kubernetes.io/component: database
type: Opaque
stringData:
  CASSANDRA_PASSWORD: "${PARAM_CASSANDRA_PASSWORD}"
