apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
  labels:
    app.kubernetes.io/name: cassandra
    app.kubernetes.io/component: database
data:
  CASSANDRA_CLUSTER_NAME: "${PARAM_CASSANDRA_CLUSTER_NAME}"
  CASSANDRA_NUM_TOKENS: "${PARAM_CASSANDRA_NUM_TOKENS}"
  CASSANDRA_ENDPOINT_SNITCH: "SimpleSnitch"
  MAX_HEAP_SIZE: "${PARAM_CASSANDRA_MAX_HEAP_SIZE}"
  HEAP_NEWSIZE: "${PARAM_CASSANDRA_HEAP_NEWSIZE}"
