apiVersion: v2
name: cuemby-etcd
description: Cuemby wrapper chart for etcd (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "3.5.18"

dependencies:
  - name: etcd
    version: "12.0.18"
    repository: oci://registry-1.docker.io/bitnamicharts
