apiVersion: v1
kind: Secret
metadata:
  name: rancher-secret
  labels:
    app.kubernetes.io/name: rancher
    app.kubernetes.io/component: rancher
type: Opaque
stringData:
  CATTLE_BOOTSTRAP_PASSWORD: "${PARAM_RANCHER_BOOTSTRAP_PASSWORD}"
