apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rancher-data
  labels:
    app.kubernetes.io/name: rancher
    app.kubernetes.io/component: rancher
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: ${PARAM_RANCHER_DATA_SIZE}
