apiVersion: v1
kind: Service
metadata:
  name: rancher
  labels:
    app.kubernetes.io/name: rancher
    app.kubernetes.io/component: rancher
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rancher
    app.kubernetes.io/component: rancher
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: ${PARAM_RANCHER_HTTPS_NODEPORT}
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      nodePort: ${PARAM_RANCHER_HTTP_NODEPORT}
      protocol: TCP
