apiVersion: v1
kind: Service
metadata:
  name: rancher-http
  labels:
    app.kubernetes.io/name: rancher
    app.kubernetes.io/component: rancher
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rancher
    app.kubernetes.io/component: rancher
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
