apiVersion: v2
name: cuemby-valkey
description: Cuemby wrapper chart for Valkey (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "8.1.1"

dependencies:
  - name: valkey
    version: "5.3.0"
    repository: oci://registry-1.docker.io/bitnamicharts
