#cloud-config
package_update: true

packages:
  - curl
  - git
  - jq

write_files:
  - path: /opt/cuemby/marketplace-env.sh
    permissions: "0600"
    content: |
      #!/usr/bin/env bash
      export APP_NAME="openbao"
      export APP_VERSION="{{app-version}}"
      export PARAM_OPENBAO_DATA_SIZE="{{param-openbao-data-size}}"
      export PARAM_OPENBAO_DEV_ROOT_TOKEN="{{param-openbao-dev-root-token}}"
      export PARAM_OPENBAO_SSL_ENABLED="{{param-openbao-ssl-enabled}}"
      export PARAM_OPENBAO_HOSTNAME="{{param-openbao-hostname}}"

runcmd:
  - git clone https://github.com/cuemby/cloud-marketplace.git /opt/cuemby/marketplace
  - [bash, -c, "source /opt/cuemby/marketplace-env.sh && /opt/cuemby/marketplace/bootstrap/entrypoint.sh 2>&1 | tee /var/log/cuemby/bootstrap.log"]
