apiVersion: v1
kind: Service
metadata:
  name: gitea-http
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/component: app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: ${PARAM_GITEA_HTTP_NODEPORT}
      protocol: TCP
