apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/component: app
  ports:
    - port: 22
      targetPort: 22
      nodePort: ${PARAM_GITEA_SSH_NODEPORT}
      protocol: TCP
