apiVersion: v1
kind: Service
metadata:
  name: gitea-web
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
