apiVersion: v1
kind: Secret
metadata:
  name: ferretdb-db-secret
  labels:
    app.kubernetes.io/name: ferretdb
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${PARAM_FERRETDB_DB_PASSWORD}"
  POSTGRES_USER: "ferretdb"
  POSTGRES_DB: "ferretdb"
