apiVersion: v1
kind: Service
metadata:
  name: ferretdb
  labels:
    app.kubernetes.io/name: ferretdb
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ferretdb
    app.kubernetes.io/component: app
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: ${PARAM_FERRETDB_NODEPORT}
      protocol: TCP
