apiVersion: v2
name: cuemby-influxdb
description: Cuemby wrapper chart for InfluxDB (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "3.4.1"

dependencies:
  - name: influxdb
    version: "7.1.20"
    repository: oci://registry-1.docker.io/bitnamicharts
