apiVersion: v2
name: cuemby-redis
description: Cuemby wrapper chart for Redis (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "8.6.0"

dependencies:
  - name: redis
    version: "25.3.0"
    repository: oci://registry-1.docker.io/bitnamicharts
