apiVersion: v1
kind: Service
metadata:
  name: APPNAME
  labels:
    app: APPNAME
spec:
  type: NodePort
  selector:
    app: APPNAME
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
