apiVersion: v1
kind: Secret
metadata:
  name: haproxy-credentials
  labels:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/component: proxy
type: Opaque
stringData:
  HAPROXY_STATS_USER: "${PARAM_HAPROXY_STATS_USER}"
  HAPROXY_STATS_PASSWORD: "${PARAM_HAPROXY_STATS_PASSWORD}"
