apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/component: proxy
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/component: proxy
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: ${PARAM_HAPROXY_HTTP_NODEPORT}
      protocol: TCP
