apiVersion: v1
kind: Service
metadata:
  name: haproxy-stats
  labels:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/component: proxy
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/component: proxy
  ports:
    - port: 8936
      targetPort: 8936
      nodePort: ${PARAM_HAPROXY_STATS_NODEPORT}
      protocol: TCP
