apiVersion: v2
name: cuemby-drupal
description: Cuemby wrapper chart for Drupal (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "11.2.3"

dependencies:
  - name: drupal
    version: "23.0.0"
    repository: oci://registry-1.docker.io/bitnamicharts
