apiVersion: v1
kind: Secret
metadata:
  name: openbao-credentials
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/component: vault
type: Opaque
stringData:
  DEV_ROOT_TOKEN_ID: "${PARAM_OPENBAO_DEV_ROOT_TOKEN}"
