apiVersion: v1
kind: Service
metadata:
  name: openbao
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/component: vault
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/component: vault
  ports:
    - port: 8200
      targetPort: 8200
      nodePort: ${PARAM_OPENBAO_NODEPORT}
      protocol: TCP
