apiVersion: v1
kind: Service
metadata:
  name: openbao-http
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/component: vault
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/component: vault
  ports:
    - name: http
      port: 80
      targetPort: 8200
      protocol: TCP
