apiVersion: v1
kind: Secret
metadata:
  name: neo4j-credentials
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/component: database
type: Opaque
stringData:
  NEO4J_AUTH: "neo4j/${PARAM_NEO4J_AUTH_PASSWORD}"
