apiVersion: v1
kind: Service
metadata:
  name: neo4j-bolt
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/component: database
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/component: database
  ports:
    - port: 7687
      targetPort: 7687
      nodePort: ${PARAM_NEO4J_BOLT_NODEPORT}
      protocol: TCP
