apiVersion: v2
name: cuemby-ghost
description: Cuemby wrapper chart for Ghost (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "6.0.5"

dependencies:
  - name: ghost
    version: "25.0.4"
    repository: oci://registry-1.docker.io/bitnamicharts
