apiVersion: v2
name: cuemby-vault
description: Cuemby wrapper chart for Vault (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "1.20.2"

dependencies:
  - name: vault
    version: "1.9.0"
    repository: oci://registry-1.docker.io/bitnamicharts
