apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: storage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/component: storage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seaweedfs
        app.kubernetes.io/component: storage
    spec:
      containers:
        - name: seaweedfs
          image: docker.io/chrislusf/seaweedfs:${PARAM_APP_IMAGE_TAG}
          command:
            - weed
          args:
            - server
            - -s3
            - -dir=/data
            - -volume.max=${PARAM_SEAWEEDFS_VOLUME_SIZE_LIMIT}
          ports:
            - name: master
              containerPort: 9333
              protocol: TCP
            - name: filer
              containerPort: 8888
              protocol: TCP
            - name: s3
              containerPort: 8333
              protocol: TCP
            - name: volume
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: seaweedfs-data
              mountPath: /data
          startupProbe:
            httpGet:
              path: /cluster/status
              port: master
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /cluster/status
              port: master
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /cluster/status
              port: master
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: ${PARAM_SEAWEEDFS_CPU_REQUEST}
              memory: ${PARAM_SEAWEEDFS_MEMORY_REQUEST}
            limits:
              cpu: ${PARAM_SEAWEEDFS_CPU_LIMIT}
              memory: ${PARAM_SEAWEEDFS_MEMORY_LIMIT}
      volumes:
        - name: seaweedfs-data
          persistentVolumeClaim:
            claimName: seaweedfs-data
