apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-s3
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: storage
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: storage
  ports:
    - port: 8333
      targetPort: 8333
      nodePort: ${PARAM_SEAWEEDFS_S3_NODEPORT}
      protocol: TCP
