apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-filer
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: storage
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: storage
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: ${PARAM_SEAWEEDFS_FILER_NODEPORT}
      protocol: TCP
