apiVersion: v1
kind: Secret
metadata:
  name: ghost-db-secret
  labels:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "${PARAM_GHOST_DB_ROOT_PASSWORD}"
  MYSQL_DATABASE: "ghost"
  MYSQL_USER: "ghost"
  MYSQL_PASSWORD: "${PARAM_GHOST_DB_PASSWORD}"
