apiVersion: v1
kind: Service
metadata:
  name: ghost-mysql
  labels:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/component: database
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
