apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/component: app
  ports:
    - port: 2368
      targetPort: 2368
      nodePort: ${PARAM_HTTP_NODEPORT}
      protocol: TCP
