apiVersion: v1
kind: Service
metadata:
  name: ghost-http
  labels:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: 2368
      protocol: TCP
