#cloud-config
package_update: true

packages:
  - curl
  - git
  - jq

write_files:
  - path: /opt/cuemby/marketplace-env.sh
    permissions: "0600"
    content: |
      #!/usr/bin/env bash
      export APP_NAME="selenium"
      export APP_VERSION="{{app-version}}"
      export PARAM_SELENIUM_CHROME_NODES="{{param-selenium-chrome-nodes}}"
      export PARAM_SELENIUM_FIREFOX_NODES="{{param-selenium-firefox-nodes}}"
      export PARAM_SELENIUM_SSL_ENABLED="{{param-selenium-ssl-enabled}}"
      export PARAM_SELENIUM_HOSTNAME="{{param-selenium-hostname}}"

runcmd:
  - git clone https://github.com/cuemby/cloud-marketplace.git /opt/cuemby/marketplace
  - [bash, -c, "source /opt/cuemby/marketplace-env.sh && /opt/cuemby/marketplace/bootstrap/entrypoint.sh 2>&1 | tee /var/log/cuemby/bootstrap.log"]
