apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus3-data
  labels:
    app.kubernetes.io/name: nexus3
    app.kubernetes.io/component: nexus3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: ${PARAM_NEXUS_DATA_SIZE}
