apiVersion: v1
kind: Service
metadata:
  name: nexus3
  labels:
    app.kubernetes.io/name: nexus3
    app.kubernetes.io/component: nexus3
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nexus3
    app.kubernetes.io/component: nexus3
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: ${PARAM_NEXUS_NODEPORT}
      protocol: TCP
