apiVersion: v1
kind: Service
metadata:
  name: nexus3-http
  labels:
    app.kubernetes.io/name: nexus3
    app.kubernetes.io/component: nexus3
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexus3
    app.kubernetes.io/component: nexus3
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP
