apiVersion: v1
kind: Secret
metadata:
  name: harbor-core-secret
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: core
type: Opaque
stringData:
  HARBOR_ADMIN_PASSWORD: "${PARAM_HARBOR_ADMIN_PASSWORD}"
  secretKey: "${PARAM_HARBOR_SECRET_KEY}"
  secret: "${PARAM_HARBOR_CORE_SECRET}"
  CSRF_KEY: "${PARAM_HARBOR_CSRF_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-db-secret
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${PARAM_HARBOR_DB_PASSWORD}"
  POSTGRES_USER: "harbor"
  POSTGRES_DB: "registry"
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-valkey-secret
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: cache
type: Opaque
stringData:
  VALKEY_PASSWORD: "${PARAM_HARBOR_VALKEY_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: registry
type: Opaque
stringData:
  REGISTRY_HTTP_SECRET: "${PARAM_HARBOR_REGISTRY_HTTP_SECRET}"
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-jobservice-secret
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: jobservice
type: Opaque
stringData:
  JOBSERVICE_SECRET: "${PARAM_HARBOR_JOBSERVICE_SECRET}"
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-token-cert
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: token-auth
type: Opaque
data:
  tls.key: "${PARAM_HARBOR_TOKEN_KEY}"
  tls.crt: "${PARAM_HARBOR_TOKEN_CERT}"
