apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-db
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: harbor
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harbor
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: harbor-db
          image: "docker.io/goharbor/harbor-db:${PARAM_APP_IMAGE_TAG}"
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: harbor-db-secret
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U harbor -d registry
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U harbor -d registry
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U harbor -d registry
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: ${PARAM_HARBOR_DB_CPU_REQUEST}
              memory: ${PARAM_HARBOR_DB_MEMORY_REQUEST}
            limits:
              cpu: ${PARAM_HARBOR_DB_CPU_LIMIT}
              memory: ${PARAM_HARBOR_DB_MEMORY_LIMIT}
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: harbor-db-data
