apiVersion: v1
kind: Service
metadata:
  name: harbor-jobservice
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: jobservice
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: jobservice
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
