apiVersion: v1
kind: Service
metadata:
  name: harbor-portal
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: portal
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: portal
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: ${PARAM_HTTPS_NODEPORT}
      protocol: TCP
