apiVersion: v1
kind: Service
metadata:
  name: harbor-portal-http
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: portal
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: portal
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
