apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "${PARAM_MARIADB_ROOT_PASSWORD}"
  MYSQL_DATABASE: "wordpress"
  MYSQL_USER: "wordpress"
  MYSQL_PASSWORD: "${PARAM_MARIADB_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-app-secret
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: app
type: Opaque
stringData:
  WORDPRESS_DB_HOST: "wordpress-mariadb:3306"
  WORDPRESS_DB_USER: "wordpress"
  WORDPRESS_DB_PASSWORD: "${PARAM_MARIADB_PASSWORD}"
  WORDPRESS_DB_NAME: "wordpress"
