apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: app
data:
  WORDPRESS_TABLE_PREFIX: "wp_"
  WORDPRESS_CONFIG_EXTRA: |
    define('WP_MEMORY_LIMIT', '256M');
    define('WP_MAX_MEMORY_LIMIT', '512M');
    define('DISALLOW_FILE_EDIT', true);
    define('WP_AUTO_UPDATE_CORE', false);
