apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: app
  ports:
    - port: 80
      targetPort: 80
      nodePort: ${PARAM_HTTP_NODEPORT}
      protocol: TCP
