apiVersion: v1
kind: Service
metadata:
  name: wordpress-http
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
