name: grafana
displayName: Grafana
description: Open source analytics and interactive visualization platform for monitoring dashboards.
category: monitoring
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/grafana/img/grafana-stack-220x234.png

chart:
  name: grafana
  repository: oci://registry-1.docker.io/bitnamicharts
  version: "12.1.8"

ssl:
  enabled: true

requirements:
  cpu: 1
  memory: 2Gi
  disk: 10Gi

versions:
  - "12.1.8"

parameters:
  - name: GRAFANA_ADMIN_USER
    displayName: Admin Username
    description: Grafana administrator username
    type: string
    required: true
    default: admin
    helmMapping: grafana.admin.user

  - name: GRAFANA_ADMIN_PASSWORD
    displayName: Admin Password
    description: Grafana administrator password
    type: password
    required: true
    helmMapping: grafana.admin.password
