apiVersion: v1
kind: Secret
metadata:
  name: odoo-db-secret
  labels:
    app.kubernetes.io/name: odoo
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${PARAM_ODOO_DB_PASSWORD}"
  POSTGRES_USER: "odoo"
  POSTGRES_DB: "odoo"
  ODOO_ADMIN_PASSWORD: "${PARAM_ODOO_ADMIN_PASSWORD}"
