apiVersion: v1
kind: Service
metadata:
  name: odoo-postgres
  labels:
    app.kubernetes.io/name: odoo
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: odoo
    app.kubernetes.io/component: database
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
