apiVersion: v1
kind: Service
metadata:
  name: odoo
  labels:
    app.kubernetes.io/name: odoo
    app.kubernetes.io/component: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: odoo
    app.kubernetes.io/component: app
  ports:
    - port: 8069
      targetPort: 8069
      nodePort: ${PARAM_ODOO_NODEPORT}
      protocol: TCP
