apiVersion: v2
name: cuemby-concourse
description: Cuemby wrapper chart for Concourse (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "7.12.1"

dependencies:
  - name: concourse
    version: "5.1.45"
    repository: oci://registry-1.docker.io/bitnamicharts
