name: prometheus
displayName: Prometheus
description: Open source monitoring and alerting toolkit for cloud-native environments.
category: monitoring
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/prometheus/img/prometheus-stack-220x234.png

chart:
  name: prometheus
  repository: oci://registry-1.docker.io/bitnamicharts
  version: "2.1.23"

requirements:
  cpu: 2
  memory: 4Gi
  disk: 20Gi

versions:
  - "2.1.23"

parameters: []
