apiVersion: v2
name: cuemby-jenkins
description: Cuemby wrapper chart for Jenkins (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "2.516.2"

dependencies:
  - name: jenkins
    version: "13.6.17"
    repository: oci://registry-1.docker.io/bitnamicharts
