apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${PARAM_KEYCLOAK_DB_PASSWORD}"
  POSTGRES_USER: "keycloak"
  POSTGRES_DB: "keycloak"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-app-secret
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: app
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: "${PARAM_KEYCLOAK_ADMIN_USER}"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "${PARAM_KEYCLOAK_ADMIN_PASSWORD}"
  KC_DB_USERNAME: "keycloak"
  KC_DB_PASSWORD: "${PARAM_KEYCLOAK_DB_PASSWORD}"
  KC_DB_URL: "jdbc:postgresql://keycloak-postgres:5432/keycloak"
