apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: app
data:
  KC_DB: "postgres"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
