apiVersion: v2
name: cuemby-harbor
description: Cuemby wrapper chart for Harbor (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "2.13.2"

dependencies:
  - name: harbor
    version: "27.0.3"
    repository: oci://registry-1.docker.io/bitnamicharts
