apiVersion: v2
name: cuemby-appsmith
description: Cuemby wrapper chart for Appsmith (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "1.52.0"

dependencies:
  - name: appsmith
    version: "7.0.3"
    repository: oci://registry-1.docker.io/bitnamicharts
