apiVersion: v2
name: cuemby-mysql
description: Cuemby wrapper chart for MySQL (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "8.4.4"

dependencies:
  - name: mysql
    version: "14.0.3"
    repository: oci://registry-1.docker.io/bitnamicharts
