apiVersion: v2
name: cuemby-kafka
description: Cuemby wrapper chart for Kafka (Bitnami upstream)
type: application
version: 1.0.0
appVersion: "3.9.0"

dependencies:
  - name: kafka
    version: "32.4.3"
    repository: oci://registry-1.docker.io/bitnamicharts
